In [1]:
import pandas as pd
import numpy as np

__First, let's grab the column names from the data dictionary provided by the client__

To do that, we read the excel sheet into a dataframe:

In [2]:
col_names_df = pd.read_excel("./iss-data/Data Dictionary.xlsx", sheet_name="IMS Data Dictionary")

In [3]:
col_names_df

,Field,Definition
0,datedim,Date that data was extracted from the Primary ...
1,id,Unique identifier for objects in the IMS database
2,id_parent,Indicator of item hierarchy. Defines the ID of...
3,id_path,Shows full hierarchy of an item's parentage. M...
4,tree_depth,Indicates how many levels deep in the hierarch...
5,tree,Defines the segment of the IMS database that a...
6,part_number,Partially unique identifier which denotes the ...
7,serial_number,Partially unique identifier which denotes the ...
8,location_name,Location within the ISS assembly of a given ob...
9,original_ip_owner,Some items on ISS transfer ownership. This fie...
10,current_ip_owner,Some items on ISS transfer ownership. This fie...
11,operational_nomenclature,Effectively = name; this field denotes the pro...
12,russian_name,Indicates the russian colloqueal name for an o...
13,english_name,Indicates the english colloqueal name for an o...
14,barcode,Partially unique object identifier used in RFI...
15,quantity,Indicates the unit quantity of a record
16,width,Dimension in mm
17,height,Dimension in mm
18,length,Dimension in mm
19,diameter,Dimension in mm
20,calculated_volume,Volume calculated from dimensional values in u...
21,stwg_ovrrd_vol,Override applied when items have known volume ...
22,children_volume,Sum of the volumes of all items which are dire...
23,stwg_ovrrd_chldren_vol,Override applied when children items have know...
24,ovrrd_notes,Explanation of applied overrides
25,volume_notes,Explanation of volume calculation algorithm ap...
26,expire_date,"Date of expiration of a given resource, where ..."
27,launch,Indicates the vehicle that an object was deliv...
28,type,"Indicates if an object is an item, container, ..."
29,hazard,Indicates any hazardous properties of an item
30,state,Indicates functional / non-functional state of...
31,status,"Indicates whether an object is Stowed, Install..."
32,is_container,Indicates if an object can contain other objects
33,is_moveable,Indicates if an object can be moved
34,system,Indicates what ISS systems the object belongs ...
35,subsystem,Indicates the ISS subsystem the object belongs...
36,action_date,Indicates the last time a given database recor...
37,move_date,Indicates the last time an object changed loca...
38,fill_status,Coarse indication of a liquid container object...
39,categoryID,ID associated with the tracking category an ob...
40,category_name,"Tracking category an object belongs to (Food, ..."

Then we select the `Field` column and transform that selection into a numpy array, which is then casted to a Python list.

In [4]:
col_names = list(col_names_df["Field"].to_numpy())

__Now that we know the column names in the provided CSV, we need to define the columns we actually need to start performing analysis.__

In [5]:
ims_cols = [
    'id',
    'part_number',
    'serial_number',
    'current_ip_owner',
    'english_name',
    'launch',
    'state',
    'status',
    'action_date',
    'move_date',
    'fill_status',
    'categoryID',
    'category_name'
]

__Finally, we read the IMS Consumables dataset.__

During the `read_csv` operation, we first apply the column names we grabbed from the data dictionary using the `names` option. Then we tell Pandas to only include the columns we defined using the `usecols` option.

In [6]:
ims_df = pd.read_csv('./iss-data/csv/inventory_mgmt_system_consumables_20220101-20230905.csv', names=col_names, usecols=ims_cols, keep_default_na=False)

Okay, we've successfully read a 42-field CSV file and we have a dataframe with only 13 columns. That seems much more manageable.

In [7]:
ims_df.head()

,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
0,364155,11Ф615.8720А55-20,1180,RSA00,SOLID WESTE CONTAINER BODY,Progress МS-13 (74P),Functional,Stowed,2020-10-10 19:22:04.180,2020-10-10 19:22:04.180,NULL,3,KTO
1,364156,11Ф615.8720А55-20,1181,RSA00,SOLID WESTE CONTAINER BODY,Progress МS-13 (74P),Functional,Stowed,2020-10-10 19:22:04.300,2020-10-10 19:22:04.300,NULL,3,KTO
2,364157,11Ф615.8720А55-20,1182,RSA00,SOLID WESTE CONTAINER BODY,Progress МS-13 (74P),Functional,Stowed,2020-10-10 19:22:04.263,2020-10-10 19:22:04.263,NULL,3,KTO
3,364158,11Ф615.8720А55-10,1182,RSA00,SOLID WASTE CONTAINER BOTTOM,Progress МS-13 (74P),Functional,Stowed,2020-10-10 19:22:04.250,2020-10-10 19:22:04.250,NULL,3,KTO
4,364160,11Ф615.8720А55-20,1184,RSA00,SOLID WESTE CONTAINER BODY,Progress МS-13 (74P),Functional,Stowed,2020-10-10 19:22:04.290,2020-10-10 19:22:04.290,NULL,3,KTO

In [8]:
ims_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5790369 entries, 0 to 5790368
Data columns (total 13 columns):
 #   Column            Dtype
---  ------            -----
 0   id                int64
 1   part_number       object
 2   serial_number     object
 3   current_ip_owner  object
 4   english_name      object
 5   launch            object
 6   state             object
 7   status            object
 8   action_date       object
 9   move_date         object
 10  fill_status       object
 11  categoryID        int64
 12  category_name     object
dtypes: int64(2), object(11)
memory usage: 574.3+ MB

In [9]:
ims_df.sort_values('action_date')

,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
1603504,385,А8-9060-400,0290217,RSA00,Sanitary inserts,2A.1,,Discard,2008-04-17 09:50:27.400,2000-09-13 14:35:37.560,NULL,4,ACY Inserts
4755949,385,А8-9060-400,0290217,RSA00,Sanitary inserts,2A.1,,Discard,2008-04-17 09:50:27.400,2000-09-13 14:35:37.560,NULL,4,ACY Inserts
100464,385,А8-9060-400,0290217,RSA00,Sanitary inserts,2A.1,,Discard,2008-04-17 09:50:27.400,2000-09-13 14:35:37.560,NULL,4,ACY Inserts
5461675,385,А8-9060-400,0290217,RSA00,Sanitary inserts,2A.1,Non-Functional,Discard,2008-04-17 09:50:27.400,2000-09-13 14:35:37.560,NULL,4,ACY Inserts
918442,385,А8-9060-400,0290217,RSA00,Sanitary inserts,2A.1,,Discard,2008-04-17 09:50:27.400,2000-09-13 14:35:37.560,NULL,4,ACY Inserts
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5777990,449094,11Ф615.8720А55-20,1348,NASA,SOLID WASTE CONTAINER - BODY,CYG17,Functional,Installed,2023-09-05 08:08:31.380,2023-09-05 08:07:52.287,NULL,3,KTO
5777991,494223,11Ф615.8720А55-10,1428,NASA,SOLID WASTE CONTAINER BOTTOM,CYG19,Functional,Installed,2023-09-05 08:08:31.397,2023-09-05 08:07:31.830,NULL,3,KTO
5777635,472037,SEG48102042-901,G0924,RSA00,BULK OVERWRAP BAG,CYG18,Functional,Stowed,2023-09-05 12:20:47.093,2023-09-05 12:20:47.093,NULL,6,Food-US
5776972,449418,SEG48102042-901,J0652,RSA00,BULK OVERWRAP BAG,CYG17,Functional,Installed,2023-09-05 12:21:33.047,2023-09-05 12:21:25.360,NULL,6,Food-US
5777500,494234,11Ф615.8720А55-20,1422,NASA,SOLID WASTE CONTAINER - BODY,CYG19,Functional,Discard,2023-09-05 16:06:16.383,2023-09-05 08:02:01.793,NULL,3,KTO

Okay, we've sorted the dataframe by `move_date`. I'm not sure whether or not we should keep items that were moved before 2022. __That sounds like a question for Devin__. For now, let's narrow the dataset again by selecting items that were moved since the beginning of 2022.

In [16]:
contemp_df = ims_df[ims_df['action_date'] > '2022-01-01 00:00:00:00']

In [17]:
contemp_df

,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
11710,422869,11Ф615.8720А55-20,1230,NASA,SOLID WASTE CONTAINER - BODY,NULL,Functional,Discard,2022-01-04 08:31:51.277,2022-01-04 08:31:51.277,NULL,3,KTO
11711,422911,11Ф615.8720А55-10,1253,NASA,SOLID WASTE CONTAINER BOTTOM,NULL,Functional,Installed,2022-01-04 18:06:24.907,2021-12-30 07:47:56.507,NULL,3,KTO
11712,237742,17КС.240Ю8711А-180,1184,NASA,EDV COVER,CYG6,Functional,Discard,2022-01-03 12:57:19.890,2022-01-03 12:56:49.960,NULL,1,EDV
11771,188153,17КС.240Ю8711А-180,1124,NASA,EDV COVER,ATV5,Functional,Installed,2022-01-03 12:39:05.320,2022-01-03 12:38:46.023,NULL,1,EDV
11788,422864,11Ф615.8720А55-20,1228,NASA,SOLID WASTE CONTAINER - BODY,NULL,Functional,Installed,2022-01-04 08:31:20.400,2022-01-04 08:31:20.400,NULL,3,KTO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5789887,73902,10146.4627.000-01,NA_FLT33P_00182,NASA,PRETREAT CONTAINER WITH A HOSE,Progress M-02М (33P),Functional,Discard,2023-04-16 13:55:15.857,2023-04-16 13:55:15.857,NULL,2,Pretreat Tanks
5789888,73922,А8-9060-400,NA_FLT33P_00186,NASA,TOILET (ACY) INSERTS,Progress M-02М (33P),Functional,Discard,2023-04-16 13:55:14.790,2023-04-16 13:55:14.790,NULL,4,ACY Inserts
5789889,73924,А8-9060-400,NA_FLT33P_00188,NASA,TOILET (ACY) INSERTS,Progress M-02М (33P),Functional,Discard,2023-04-16 13:55:14.803,2023-04-16 13:55:14.803,NULL,4,ACY Inserts
5789890,76223,А8-9060-400,0390501,NASA,TOILET (АСУ) INSERTS,Progress M-67 (34P),Functional,Stowed,2023-04-16 13:55:14.403,2023-04-16 13:55:14.403,NULL,4,ACY Inserts
5790368,465769,А8-9060-400,NA_INC67_271_1,NASA,TOILET (АСУ) INSERTS,NULL,Functional,Stowed,2022-09-30 19:24:29.263,2022-09-30 19:24:29.263,NULL,4,ACY Inserts

Now we're down to just over 1 million items. We can see that some of the items are owned by RSA and some by NASA. Let's assume (for now) that we're only concerned about items that NASA owns. We can filter the dataset so it no longer includes items where `current_ip_owner` is `RSA00`.

__Note__: I sent Mason an email to ask Devin whether we should be concerned with items that are listed as having a `current_ip_owner` of `RSA00`.

In [20]:
contemp_us_only = contemp_df[contemp_df['current_ip_owner'] != 'RSA00'].sort_values('action_date')

In [21]:
contemp_us_only

,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
31230,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
19320,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
46793,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
54586,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
23446,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5777108,470813,SEG48102042-901,H0792,NASA,BULK OVERWRAP BAG,CYG18,Functional,Installed,2023-09-04 15:34:06.680,2023-09-04 12:08:39.290,NULL,6,Food-US
5777386,473517,SEG48102042-901,H0796,NASA,BULK OVERWRAP BAG,DRA26,Functional,Discard,2023-09-04 15:34:32.447,2023-09-04 15:34:32.447,NULL,6,Food-US
5777990,449094,11Ф615.8720А55-20,1348,NASA,SOLID WASTE CONTAINER - BODY,CYG17,Functional,Installed,2023-09-05 08:08:31.380,2023-09-05 08:07:52.287,NULL,3,KTO
5777991,494223,11Ф615.8720А55-10,1428,NASA,SOLID WASTE CONTAINER BOTTOM,CYG19,Functional,Installed,2023-09-05 08:08:31.397,2023-09-05 08:07:31.830,NULL,3,KTO
5777500,494234,11Ф615.8720А55-20,1422,NASA,SOLID WASTE CONTAINER - BODY,CYG19,Functional,Discard,2023-09-05 16:06:16.383,2023-09-05 08:02:01.793,NULL,3,KTO

We've narrowed the whole dataframe to ten-percent of its original size through filtering. One other thing to notice, is that there appear to be multiple entries with the same `id`. According to the Data Dictionary, that's supposed to be unique for each item, so I don't know what it means to have an item entered multiple times. Let's group by `id` and see how many entries with the matching ids are entered.

In [22]:
test_item_1 = contemp_us_only[contemp_us_only['id'] == 440727]

In [23]:
test_item_1

,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
31230,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
19320,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
46793,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
54586,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
23446,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4093535,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,DRA24,Functional,Discard,2022-06-28 16:37:36.483,2022-06-28 16:37:36.483,NULL,6,Food-US
3729901,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,DRA24,Functional,Discard,2022-06-28 16:37:36.483,2022-06-28 16:37:36.483,NULL,6,Food-US
1830341,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Discard,2022-06-28 16:37:36.483,2022-06-28 16:37:36.483,NULL,6,Food
4989882,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,DRA24,Functional,Discard,2022-06-28 16:37:36.483,2022-06-28 16:37:36.483,NULL,6,Food-US
4910256,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,DRA24,Functional,Discard,2022-06-28 16:37:36.483,2022-06-28 16:37:36.483,NULL,6,Food-US

In [51]:
contemp_id_groups = contemp_us_only.groupby(['id'])

In [55]:
contemp_id_groups.apply(lambda x: x).drop_duplicates().sort_values('action_date')

,,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
id,,,,,,,,,,,,,,
440727,31230,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
407582,109045,407582,SEG48102042-901,N0104,NASA,BULK OVERWRAP BAG,CYG15,Functional,Installed,2022-01-02 17:44:12.413,2022-01-02 17:44:12.413,NULL,6,Food
407577,31210,407577,SEG48102042-901,J0600,NASA,BULK OVERWRAP BAG,CYG15,Functional,Installed,2022-01-02 17:44:35.643,2022-01-02 17:44:35.643,NULL,6,Food
409231,19302,409231,SEG48102042-901,Z0720,NASA,BULK OVERWRAP BAG,CYG15,Functional,Installed,2022-01-02 17:45:09.643,2022-01-02 17:45:09.643,NULL,6,Food
409270,19303,409270,SEG48102042-901,G0784,NASA,BULK OVERWRAP BAG,CYG15,Functional,Installed,2022-01-02 17:45:32.567,2022-01-02 17:45:32.567,NULL,6,Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470813,5777108,470813,SEG48102042-901,H0792,NASA,BULK OVERWRAP BAG,CYG18,Functional,Installed,2023-09-04 15:34:06.680,2023-09-04 12:08:39.290,NULL,6,Food-US
473517,5777386,473517,SEG48102042-901,H0796,NASA,BULK OVERWRAP BAG,DRA26,Functional,Discard,2023-09-04 15:34:32.447,2023-09-04 15:34:32.447,NULL,6,Food-US
449094,5777990,449094,11Ф615.8720А55-20,1348,NASA,SOLID WASTE CONTAINER - BODY,CYG17,Functional,Installed,2023-09-05 08:08:31.380,2023-09-05 08:07:52.287,NULL,3,KTO
494223,5777991,494223,11Ф615.8720А55-10,1428,NASA,SOLID WASTE CONTAINER BOTTOM,CYG19,Functional,Installed,2023-09-05 08:08:31.397,2023-09-05 08:07:31.830,NULL,3,KTO
494234,5777500,494234,11Ф615.8720А55-20,1422,NASA,SOLID WASTE CONTAINER - BODY,CYG19,Functional,Discard,2023-09-05 16:06:16.383,2023-09-05 08:02:01.793,NULL,3,KTO

Well, that's interesting. The entire set of unique entries is just a bit more than 2,000 items. We definitely want to ask Devin what multiple recurring `id`s means.

In [61]:
contemp_us_only.index = pd.to_datetime(contemp_us_only['action_date'])

In [62]:
contemp_us_only

,id,part_number,serial_number,current_ip_owner,english_name,launch,state,status,action_date,move_date,fill_status,categoryID,category_name
action_date,,,,,,,,,,,,,
2022-01-02 17:43:46.743,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
2022-01-02 17:43:46.743,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
2022-01-02 17:43:46.743,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
2022-01-02 17:43:46.743,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
2022-01-02 17:43:46.743,440727,SEG48102042-901,Q0620,NASA,BULK OVERWRAP BAG,NULL,Functional,Installed,2022-01-02 17:43:46.743,2022-01-02 17:43:46.743,NULL,6,Food
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-09-04 15:34:06.680,470813,SEG48102042-901,H0792,NASA,BULK OVERWRAP BAG,CYG18,Functional,Installed,2023-09-04 15:34:06.680,2023-09-04 12:08:39.290,NULL,6,Food-US
2023-09-04 15:34:32.447,473517,SEG48102042-901,H0796,NASA,BULK OVERWRAP BAG,DRA26,Functional,Discard,2023-09-04 15:34:32.447,2023-09-04 15:34:32.447,NULL,6,Food-US
2023-09-05 08:08:31.380,449094,11Ф615.8720А55-20,1348,NASA,SOLID WASTE CONTAINER - BODY,CYG17,Functional,Installed,2023-09-05 08:08:31.380,2023-09-05 08:07:52.287,NULL,3,KTO
2023-09-05 08:08:31.397,494223,11Ф615.8720А55-10,1428,NASA,SOLID WASTE CONTAINER BOTTOM,CYG19,Functional,Installed,2023-09-05 08:08:31.397,2023-09-05 08:07:31.830,NULL,3,KTO
2023-09-05 16:06:16.383,494234,11Ф615.8720А55-20,1422,NASA,SOLID WASTE CONTAINER - BODY,CYG19,Functional,Discard,2023-09-05 16:06:16.383,2023-09-05 08:02:01.793,NULL,3,KTO